# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tugo/leads/v1/common/response.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tugo/leads/v1/common/response.proto", :syntax => :proto3) do
    add_message "tugo.leads.v1.common.CommonMasterResponse" do
      repeated :common_master, :message, 1, "tugo.leads.v1.common.CommonMaster"
    end
    add_message "tugo.leads.v1.common.CommonMaster" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
      optional :name, :message, 2, "google.protobuf.StringValue"
    end
  end
end

module Tugo
  module Leads
    module V1
      module Common
        CommonMasterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.leads.v1.common.CommonMasterResponse").msgclass
        CommonMaster = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tugo.leads.v1.common.CommonMaster").msgclass
      end
    end
  end
end
