# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tugo/leads/v1/master.proto for package 'tugo.leads.v1'

require 'grpc'
require 'tugo/leads/v1/master_pb'

module Tugo
  module Leads
    module V1
      module MasterService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tugo.leads.v1.MasterService'

          # --
          # cmn_00016 Get Table Master
          # --
          rpc :ListMaster, ::Tugo::Leads::V1::ListMasterRequest, ::Tugo::Leads::V1::Common::CommonMasterResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
