# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tugo/common/v1/group.proto for package 'tugo.common.v1'

require 'grpc'
require 'tugo/common/v1/group_pb'

module Tugo
  module Common
    module V1
      module GroupService
        class Service
          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tugo.common.v1.GroupService'

          # --
          # cmn_00001 Get Group By Id
          # --
          rpc :GetGroupById, ::Tugo::Common::V1::GroupIdRequest, ::Tugo::Common::V1::GroupResponse
          # --
          # cmn_00002 Get Groups
          # --
          rpc :GetGroups, ::Google::Protobuf::Empty, ::Tugo::Common::V1::GroupsResponse
          # --
          # cmn_00003 Upsert Group
          # --
          rpc :UpsertGroup, ::Tugo::Common::V1::UpsertGroupRequest, ::Tugo::Common::V1::UpsertGroupResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
