# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tugo/common/v1/master.proto for package 'tugo.common.v1'

require 'grpc'
require 'tugo/common/v1/master_pb'

module Tugo
  module Common
    module V1
      module MasterService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tugo.common.v1.MasterService'

          # --
          # cmn_00011 Get Countries and Provinces and Districts
          # --
          rpc :GetCountriesProvincesDistricts, ::Google::Protobuf::Empty, ::Tugo::Common::V1::CountriesProvincesDistrictsResponse
          # --
          # cmn_00012 Get Wards By District ID
          # --
          rpc :GetWardsByDistrictId, ::Tugo::Common::V1::DistrictIdRequest, ::Tugo::Common::V1::WardsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
