# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tugo/common/v1/role.proto for package 'tugo.common.v1'

require 'grpc'
require 'tugo/common/v1/role_pb'

module Tugo
  module Common
    module V1
      module RoleService
        class Service
          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tugo.common.v1.RoleService'

          # --
          # cmn_00004 Get Role By Id
          # --
          rpc :GetRoleById, ::Tugo::Common::V1::RoleIdRequest, ::Tugo::Common::V1::RoleResponse
          # --
          # cmn_00005 Get Roles
          # --
          rpc :GetRoles, ::Google::Protobuf::Empty, ::Tugo::Common::V1::RolesResponse
          # --
          # cmn_00006 Upsert Role
          # --
          rpc :UpsertRole, ::Tugo::Common::V1::UpsertRoleRequest, ::Tugo::Common::V1::UpsertRoleResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
