# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tugo/common/v1/user.proto for package 'tugo.common.v1'

require 'grpc'
require 'tugo/common/v1/user_pb'

module Tugo
  module Common
    module V1
      module UserService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'tugo.common.v1.UserService'

          # --
          # cmn_00007 Get User By User Name
          # --
          rpc :GetUserByUserName, ::Tugo::Common::V1::UserNameRequest, ::Tugo::Common::V1::UserResponse
          # --
          # cmn_00008 Get Users
          # --
          rpc :GetUsers, ::Google::Protobuf::Empty, ::Tugo::Common::V1::UsersResponse
          # --
          # cmn_00009 Upsert User
          # --
          rpc :UpsertUser, ::Tugo::Common::V1::UpsertUserRequest, ::Tugo::Common::V1::UpsertUserResponse
          # --
          # cmn_00010 User Login
          # --
          rpc :UserLogin, ::Tugo::Common::V1::LoginInfoRequest, ::Tugo::Common::V1::UserResponse
          # --
          # cmn_00013 Get User By User Id
          # --
          rpc :GetUserById, ::Tugo::Common::V1::UserIdRequest, ::Tugo::Common::V1::UserResponse
          # --
          # cmn_00014 Function to get subordinates Users
          # --
          rpc :GetRoleBasedSubordinateUsers, ::Tugo::Common::V1::UserIdRequest, ::Tugo::Common::V1::UsersResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
