# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tugo/organizations/v1/organization.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('tugo/organizations/v1/organization.proto', syntax: :proto3) do
    add_message 'tugo.organizations.v1.OrganizationIdRequest' do
      optional :organization_id, :message, 1, 'google.protobuf.Int64Value'
    end
    add_message 'tugo.organizations.v1.OrganizationResponse' do
      optional :organization, :message, 1, 'tugo.organizations.v1.Organization'
    end
    add_message 'tugo.organizations.v1.OrganizationOwnerIdRequest' do
      optional :owner_id, :message, 1, 'google.protobuf.Int64Value'
    end
    add_message 'tugo.organizations.v1.OrganizationsResponse' do
      repeated :organizations, :message, 1, 'tugo.organizations.v1.Organization'
    end
    add_message 'tugo.organizations.v1.UpsertOrganizationRequest' do
      optional :organization, :message, 1, 'tugo.organizations.v1.Organization'
    end
    add_message 'tugo.organizations.v1.UpsertOrganizationResponse' do
      optional :organization, :message, 1, 'tugo.organizations.v1.Organization'
    end
    add_message 'tugo.organizations.v1.UpsertOrganizationsRequest' do
      repeated :organizations, :message, 1, 'tugo.organizations.v1.Organization'
    end
    add_message 'tugo.organizations.v1.UpsertOrganizationsResponse' do
      repeated :organizations, :message, 1, 'tugo.organizations.v1.Organization'
    end
    add_message 'tugo.organizations.v1.Organization' do
      optional :id, :message, 1, 'google.protobuf.Int64Value'
      optional :organization_name, :message, 2, 'google.protobuf.StringValue'
      optional :phone, :message, 3, 'google.protobuf.StringValue'
      optional :email, :message, 4, 'google.protobuf.StringValue'
      optional :website, :message, 5, 'google.protobuf.StringValue'
      optional :employees, :message, 6, 'google.protobuf.Int64Value'
      optional :annual_revenue, :message, 7, 'google.protobuf.DoubleValue'
      optional :master_industry_id, :message, 8, 'google.protobuf.Int64Value'
      optional :master_type_id, :message, 9, 'google.protobuf.Int64Value'
      optional :master_status_id, :message, 10, 'google.protobuf.Int64Value'
      optional :address, :message, 11, 'google.protobuf.StringValue'
      optional :master_ward_id, :message, 12, 'google.protobuf.Int64Value'
      optional :master_district_id, :message, 13, 'google.protobuf.Int64Value'
      optional :master_province_id, :message, 14, 'google.protobuf.Int64Value'
      optional :master_country_id, :message, 15, 'google.protobuf.Int64Value'
      optional :description, :message, 16, 'google.protobuf.StringValue'
      optional :creator_id, :message, 17, 'google.protobuf.Int64Value'
      optional :owner_id, :message, 18, 'google.protobuf.Int64Value'
      optional :modified_by_id, :message, 19, 'google.protobuf.Int64Value'
      optional :created_at, :message, 20, 'google.protobuf.StringValue'
      optional :updated_at, :message, 21, 'google.protobuf.StringValue'
    end
  end
end

module Tugo
  module Organizations
    module V1
      OrganizationIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('tugo.organizations.v1.OrganizationIdRequest').msgclass
      OrganizationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('tugo.organizations.v1.OrganizationResponse').msgclass
      OrganizationOwnerIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('tugo.organizations.v1.OrganizationOwnerIdRequest').msgclass
      OrganizationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('tugo.organizations.v1.OrganizationsResponse').msgclass
      UpsertOrganizationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('tugo.organizations.v1.UpsertOrganizationRequest').msgclass
      UpsertOrganizationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('tugo.organizations.v1.UpsertOrganizationResponse').msgclass
      UpsertOrganizationsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('tugo.organizations.v1.UpsertOrganizationsRequest').msgclass
      UpsertOrganizationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('tugo.organizations.v1.UpsertOrganizationsResponse').msgclass
      Organization = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('tugo.organizations.v1.Organization').msgclass
    end
  end
end
